### ISSUE TITLE
libpopt Static Library

### ISSUE THREAD

**Issue by tmbarton** [cygwinports/popt#1]
Currently only shared library is built at least for the 64-bit package.  The libpopt-devel package only provides libpopt.dll.a and not the static library libpopt.a.  Neither is it available in the libpopt0 or libpopt-common packages.

**Comment by yselkowitz** [comment]
Static libraries are not generally built for Cygwin.

**Comment by tmbarton** [comment]
Perhaps I am using the wrong terminology.  The program that uses it has linked successfully for years using "-lpopt" to gcc on the 32-bit versions of cygwin.  However in doesn't link on my up-to-date 64-bit installation, because libpopt.a is no longer available.  I guess it used to be available to make the link work, however I no longer have the 32-bit installation available to verify that.  Nevertheless it did link without errors on the 32-bit installation and now does not on the 64-bit, error message being "cannot find  -lpopt". Changing the compiler flag to "-lpopt.dll" does work, but then clearly it won't link on a linux system without changes to the makefile.

**Comment by yselkowitz** [comment]
Sounds like you are linking with -static.  Don't do that, and -lpopt will work just fine.

**Comment by tmbarton** [comment]
Thank you, I was.  Not sure why I was, but removing that indeed fixed the problem. :)
